site_name: Servv WordPress Docs
theme:
  name: material
  palette:
    primary: blue
    accent: light blue
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Changelog: changelog.md
repo_url: https://github.com/varuncoderise/demo_docs
edit_uri: edit/main/docs/